"use client";

import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import { BookOpen, Code, GitPullRequest, Lightbulb } from "lucide-react";

type CategoryVariant = "identity" | "architecture" | "consistency" | "engineering";

export interface RoadmapItemData {
    title: string;
    description: string;
    category: CategoryVariant;
}

interface AiRoadmapProps {
    roadmap?: RoadmapItemData[];
}

const getCategoryStyles = (category: string) => {
    switch (category) {
        case "identity":
            return {
                icon: <GitPullRequest className="w-[18px] h-[18px]" />,
                container: "border-purple-500/20",
                iconBg: "bg-purple-500/10 border-purple-500/20 text-[#d2a8ff]",
                badge: "bg-purple-500/10 border-purple-500/20 text-[#d2a8ff]"
            };
        case "architecture":
            return {
                icon: <BookOpen className="w-[18px] h-[18px]" />,
                container: "border-blue-500/20",
                iconBg: "bg-blue-500/10 border-blue-500/20 text-[#79c0ff]",
                badge: "bg-blue-500/10 border-blue-500/20 text-[#79c0ff]"
            };
        case "consistency":
            return {
                icon: <Code className="w-[18px] h-[18px]" />,
                container: "border-emerald-500/20",
                iconBg: "bg-emerald-500/10 border-emerald-500/20 text-[#7ee787]",
                badge: "bg-emerald-500/10 border-emerald-500/20 text-[#7ee787]"
            };
        default:
            return {
                icon: <Lightbulb className="w-[18px] h-[18px]" />,
                container: "border-orange-500/20",
                iconBg: "bg-orange-500/10 border-orange-500/20 text-orange-400",
                badge: "bg-orange-500/10 border-orange-500/20 text-orange-400"
            };
    }
};

export default function AiRoadmap({ roadmap }: AiRoadmapProps) {
    if (!roadmap || roadmap.length === 0) return null;
    return (
        <section className="w-full max-w-4xl mx-auto py-8">
            <div className="mb-10">
                <h2 className="text-3xl font-bold text-white tracking-tight">AI Engineering Roadmap</h2>
                <p className="text-[#8b949e] text-[15px] mt-2">
                    Personalized actionable advice generated by Gemini based on your unique repository metrics.
                </p>
            </div>

            <div className="flex flex-col gap-0 relative">
                {/* Continuous Timeline Line */}
                <div className="absolute left-[19px] top-6 bottom-8 w-px bg-[#21262d]" />

                {roadmap.map((item, i) => {
                    const style = getCategoryStyles(item.category);

                    return (
                        <motion.div
                            key={i}
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: i * 0.15 }}
                            className="relative pl-14 pb-8 last:pb-0"
                        >
                            {/* Icon Wrapper */}
                            <div className="absolute left-0 top-3">
                                <div className={cn(
                                    "w-10 h-10 rounded-full border flex items-center justify-center z-10 relative bg-[#0d1117]",
                                    style.iconBg
                                )}>
                                    {style.icon}
                                </div>
                            </div>

                            {/* Content Card */}
                            <div className="border border-[#30363d] bg-[#161b22]/40 rounded-2xl p-6 transition-colors hover:bg-[#161b22]/60">
                                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                                    <div className="flex-1 pr-6">
                                        <h3 className="text-white font-semibold text-[17px] tracking-tight">{item.title}</h3>
                                        <p className="text-[#8b949e] text-[15px] mt-2 leading-relaxed">
                                            {item.description}
                                        </p>
                                    </div>
                                    <div className="flex-shrink-0 self-start sm:self-center">
                                        <span className={cn(
                                            "text-[11px] font-bold uppercase tracking-wider px-3.5 py-1.5 rounded-lg border",
                                            style.badge
                                        )}>
                                            {item.category}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </motion.div>
                    );
                })}
            </div>
        </section>
    );
}
