"use client";

import Header from "@/components/layout/Header";
import ScoreOverview from "@/components/dashboard/ScoreOverview";
import MetricsGrid from "@/components/dashboard/MetricsGrid";
import Roadmap from "@/components/dashboard/Roadmap";
import DashboardSkeleton from "@/components/ui/DashboardSkeleton";
import Link from "next/link";
import { motion } from "framer-motion";

import { useEffect, useState, Suspense } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { AlertTriangle } from "lucide-react";

function DashboardContent() {
    const searchParams = useSearchParams();
    const router = useRouter();
    const username = searchParams.get("user");

    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [data, setData] = useState<any>(null);

    useEffect(() => {
        if (!username) {
            router.push('/');
            return;
        }

        const fetchData = async () => {
            try {
                const res = await fetch('/api/analyze', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ githubUrl: `https://github.com/${username}` })
                });

                const json = await res.json();
                if (!res.ok) throw new Error(json.error || 'Failed to fetch data');
                setData(json);
            } catch (err: any) {
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        fetchData();
    }, [username, router]);

    if (loading) {
        return <DashboardSkeleton />;
    }

    if (error || !data) {
        return (
            <div className="min-h-screen bg-[#0d1117] flex items-center justify-center p-4">
                <div className="bg-red-500/10 border border-red-500/20 text-red-400 p-6 rounded-2xl shadow-xl flex flex-col items-center max-w-md text-center">
                    <AlertTriangle className="w-12 h-12 mb-4 text-red-500" />
                    <h2 className="text-xl font-bold mb-2">Analysis Failed</h2>
                    <p className="text-sm leading-relaxed mb-6">{error || 'Unknown error occurred'}</p>
                    <button
                        onClick={() => router.push('/')}
                        className="bg-red-500/20 hover:bg-red-500/30 text-red-300 font-semibold px-6 py-2 rounded-xl transition-colors"
                    >
                        Return Home
                    </button>
                </div>
            </div>
        );
    }
    return (
        <div className="min-h-screen bg-[#0d1117] flex flex-col">
            {/* Dark header */}
            <Header variant="dark" score={data.overallScore} />

            {/* Main */}
            <motion.main
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, ease: "easeOut" }}
                className="flex-1 flex flex-col pt-8"
            >
                {/* Score ring section */}
                <ScoreOverview
                    score={data.overallScore}
                    title="Engineering Readiness Score"
                    subtitle={`Based on the live analysis of their repositories, documentation standards, and overall tech stack diversity.`}
                />

                {/* Metrics grid */}
                <MetricsGrid metrics={data.metrics} />

                {/* AI Roadmap Generated by Gemini */}
                <Roadmap roadmap={data.roadmap} />

                {/* Stats bar */}
                <div className="w-full max-w-4xl mx-auto px-4 mt-8 mb-4">
                    <div className="glass-card rounded-2xl p-5 flex flex-wrap items-center gap-6">
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase tracking-widest text-gray-500 font-semibold">
                                Total Analyzed
                            </span>
                            <span className="text-white font-bold text-xl mt-0.5">
                                {data.metrics.commits > 0 ? 'Data Available' : 'No Data'}
                            </span>
                        </div>
                        <div className="w-px h-10 bg-white/[0.06] hidden sm:block" />
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase tracking-widest text-gray-500 font-semibold">
                                Commits (1yr)
                            </span>
                            <span className="text-white font-bold text-xl mt-0.5">
                                {data.metrics.commits.toLocaleString()}
                            </span>
                        </div>
                        <div className="w-px h-10 bg-white/[0.06] hidden sm:block" />
                        <div className="flex flex-col">
                            <span className="text-[10px] uppercase tracking-widest text-gray-500 font-semibold">
                                PRs Merged
                            </span>
                            <span className="text-white font-bold text-xl mt-0.5">
                                {data.metrics.mergedPRs}
                            </span>
                        </div>
                        <div className="ml-auto">
                            <Link
                                href="#"
                                className="text-blue-400 hover:text-blue-300 text-sm font-medium transition-colors"
                            >
                                View Detailed Repository Breakdown →
                            </Link>
                        </div>
                    </div>
                </div>
            </motion.main>

            {/* Footer */}
            <footer className="border-t border-white/[0.06] py-5 px-6 mt-6">
                <div className="max-w-7xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full overflow-hidden border border-blue-500/30">
                            {/* In a real app we would use data.profile.avatar_url, but based on mock expectations sticking to the fallback initial */}
                            <div className="w-full h-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center">
                                <span className="text-white text-xs font-bold">{data.username.charAt(0).toUpperCase()}</span>
                            </div>
                        </div>
                        <div>
                            <p className="text-white text-sm font-semibold">{data.username}</p>
                            <p className="text-gray-500 text-xs">github.com/{data.username}</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-6">
                        {["Privacy Policy", "Documentation", "Contact Support"].map((item) => (
                            <Link key={item} href="#" className="text-gray-500 hover:text-gray-300 text-xs transition-colors">
                                {item}
                            </Link>
                        ))}
                        <span className="text-gray-600 text-xs">© 2024 DevGrade AI</span>
                    </div>
                </div>
            </footer>
        </div>
    );
}

export default function DashboardPage() {
    return (
        <Suspense fallback={<DashboardSkeleton />}>
            <DashboardContent />
        </Suspense>
    );
}
