"use client";

import { cn } from "@/lib/utils";
import { motion } from "framer-motion";
import { BookOpen, Code, Github, Lightbulb, ArrowRight } from "lucide-react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";

type CategoryVariant = "identity" | "architecture" | "consistency" | "engineering";

interface RoadmapItem {
    title: string;
    description: string;
    category: CategoryVariant;
}

const categoryStyles: Record<CategoryVariant, string> = {
    identity: "bg-purple-500/10 text-purple-400 border border-purple-500/20",
    architecture: "bg-blue-500/10 text-blue-400 border border-blue-500/20",
    consistency: "bg-teal-500/10 text-teal-400 border border-teal-500/20",
    engineering: "bg-orange-500/10 text-orange-400 border border-orange-500/20",
};

const categoryIcons: Record<CategoryVariant, React.ReactNode> = {
    identity: <Github className="w-4 h-4 text-purple-400" />,
    architecture: <BookOpen className="w-4 h-4 text-blue-400" />,
    consistency: <Code className="w-4 h-4 text-teal-400" />,
    engineering: <Lightbulb className="w-4 h-4 text-orange-400" />,
};

interface RoadmapProps {
    roadmap: RoadmapItem[];
}

export default function Roadmap({ roadmap }: RoadmapProps) {
    const searchParams = useSearchParams();
    const user = searchParams?.get("user") || "";

    if (!roadmap || roadmap.length === 0) return null;

    return (
        <section className="w-full max-w-4xl mx-auto px-4 mt-8">
            <div className="mb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
                <div className="flex flex-col gap-1">
                    <h2 className="text-xl font-bold text-white">AI Engineering Roadmap</h2>
                    <p className="text-gray-400 text-sm">Personalized actionable advice generated by Gemini based on your unique repository metrics.</p>
                </div>
                <Link
                    href={`/roadmap${user ? `?user=${user}` : ""}`}
                    className="flex items-center gap-2 text-sm font-semibold text-blue-400 hover:text-blue-300 transition-colors bg-blue-500/10 hover:bg-blue-500/20 px-4 py-2 rounded-xl whitespace-nowrap self-start sm:self-auto"
                >
                    View Detailed Roadmap <ArrowRight className="w-4 h-4" />
                </Link>
            </div>

            <div className="flex flex-col gap-0">
                {roadmap.map((m, i) => {
                    const variant = Object.keys(categoryStyles).includes(m.category)
                        ? m.category
                        : "engineering";

                    return (
                        <motion.div
                            key={i}
                            initial={{ opacity: 0, x: -16 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: 0.1 + i * 0.12 }}
                            className="relative pl-10 pb-4"
                        >
                            {/* Timeline line */}
                            {i < roadmap.length - 1 && (
                                <div className="absolute left-3.5 top-8 bottom-0 w-px bg-white/[0.06]" />
                            )}

                            {/* Icon */}
                            <div className={cn(
                                "absolute left-0 top-0.5 w-7 h-7 rounded-full border flex items-center justify-center",
                                "bg-white/[0.04] border-white/[0.1]"
                            )}>
                                {categoryIcons[variant]}
                            </div>

                            <div className="glass-card rounded-xl p-4 transition-colors">
                                <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-3">
                                    <div className="flex-1 min-w-0">
                                        <h3 className="text-white font-semibold text-sm">{m.title}</h3>
                                        <p className="text-gray-400 text-xs mt-1.5 leading-relaxed">{m.description}</p>
                                    </div>
                                    <div className="flex items-center gap-2 flex-shrink-0 self-start">
                                        <span className={cn(
                                            "text-[10px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-md",
                                            categoryStyles[variant]
                                        )}>
                                            {variant}
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </motion.div>
                    );
                })}
            </div>
        </section>
    );
}
